gan:

  model_name: RecurrentGAN # RNN, GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RecurrentConvDSGAN
  epochs: 2000
  batch_size: 32
  loss_function: kl # kl, w, ds
  learning_rate: 0.0005
  discriminator_epochs: 3

  noise_vector_size: 50

  window_size: 24
  forecast_horizon: 12
  recurrent_forecasting: True # True, False
  mc_forward_passes: 5000
  plot_rate: 100

data:
  data_source: oslo # sine, oslo, australia
  test_split: 0.2

cross_validation_setup:
  k-folds: 5