gan:
  model_name: RecurrentConvGAN # GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RNN
  epochs: 3000
  batch_size: 256
  wasserstein_loss: False # True, False
  learning_rate: 0.0005
  discriminator_epochs: 50
  noise_vector_size: 1

  window_size: 12
  forecast_horizon: 24
  recurrent_forecasting: True # True, False
  mc_forward_passes: 2000
  plot_rate: 25

data:
  data_source: oslo # sine, oslo
  test_split: 0.2

cross_validation_setup:
  k-folds: 5