gan:
  model_name: RecurrentConvGAN # GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RNN
  epochs: 10000
  batch_size: 64
  wasserstein_loss: True # True, False
  learning_rate: 0.0005
  discriminator_epochs: 3
  noise_vector_size: 10

  window_size: 24
  forecast_horizon: 12
  recurrent_forecasting: True # True, False
  mc_forward_passes: 500
  plot_rate: 25

data:
  data_source: oslo # sine, oslo
  test_split: 0.2

cross_validation_setup:
  k-folds: 5