gan:
  model_name: RecurrentConvGAN # GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RNN
  epochs: 1500
  batch_size: 256
  wasserstein_loss: True # True, False
  learning_rate: 0.01
  discriminator_epochs: 10
  window_size: 24
  forecast_horizon: 12
  recurrent_forecasting: True # True, False
  mc_forward_passes: 5000
  plot_rate: 25

data:
  data_source: Oslo # sine, oslo
  test_split: 0.2