gan:
  model_name: RecurrentConvGAN # GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN
  epochs: 4000
  batch_size: 256
  wasserstein_loss: False # True, False
  learning_rate: 0.0005
  discriminator_epochs: 1
  window_size: 24
  forecast_horizon: 12
  recurrent_forecasting: False # True, False
  mc_forward_passes: 5000
  plot_rate: 25

data:
  data_source: oslo # sine, oslo
  test_split: 0.2