model_name: RecurrentGAN # RNN, ES, ARIMA, GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RecurrentConvDSGAN, RecurrentConditionalGAN
loss_function: kl # kl, w, ds

epochs: 30000
batch_size: 64
learning_rate: 0.0001
discriminator_epochs: 4

layers: rnn  # rnn, lstm, gru
number_of_recurrent_layers: 2
generator_nodes: 16
discriminator_nodes: 64
batch_norm: True # True, False
dropout: False # True, False
noise_vector_size: 100
noise_type: gaussian # gaussian (default), uniform

window_size: 26
forecast_horizon: 13
recurrent_forecasting: True # True, False
mc_forward_passes: 1000
plot_rate: 1000

print_coverage: True # True, False, Will slow down training, but print coverage during training
save_model_interval: 100

data_source: avocado # sine, oslo, australia, avocado
val_split: 0.1
test_split: 0.2
scaler: MinMax # MinMax (default), Robust, Standard

new_training_loop: True #True, False
mixed_batches: False

cross_validation_setup:
  k-folds: 5