gan:
  model_name: RecurrentConvWGAN # GAN, WGAN, ConvGAN, ConvWGAN, RecurrentGAN, RecurrentWGAN, RecurrentConvGAN, RecurrentConvWGAN

data:
  data_source: sine # sine, airpassengers
  test_split: 0.2