model_name: RecurrentGAN # RNN, ES, ARIMA, GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RecurrentConvDSGAN
loss_function: kl # kl, w, ds

epochs: 1500
batch_size: 64
learning_rate: 0.001
discriminator_epochs: 1

generator_nodes: 16
discriminator_nodes: 64
noise_vector_size: 50
noise_type: gaussian # gaussian (standard), uniform

window_size: 24
forecast_horizon: 12
recurrent_forecasting: True # True, False
mc_forward_passes: 1000
plot_rate: 25

print_coverage: True # True, False, Will slow down training, but print coverage during training
save_model_interval: 100

data_source: sine # sine, oslo, australia
test_split: 0.5

cross_validation_setup:
  k-folds: 5