model_name: RNN # RNN, ES, ARIMA, GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RecurrentConvDSGAN, RecurrentConditionalGAN
loss_function: kl # kl, w, ds

epochs: 502
batch_size: 64
learning_rate: 0.0001
discriminator_epochs: 5

layers: lstm  # rnn, lstm, gru
number_of_recurrent_layers: 1
generator_nodes: 64
discriminator_nodes: 256
batch_norm: True # True, False
dropout: False # True, False
noise_vector_size: 100
noise_type: gaussian # gaussian (default), uniform

window_size: 336
forecast_horizon: 48
recurrent_forecasting: True # True, False
mc_forward_passes: 200
plot_rate: 500

print_coverage: True # True, False, Will slow down training, but print coverage during training
save_model_interval: 1000

data_source: electricity # sine, oslo, australia, avocado, electricity
val_split: 0.1
test_split: 0.2
scaler: MinMax # MinMax (default), Robust, Standard

new_training_loop: True #True, False
mixed_batches: False

cross_validation_setup:
  k-folds: 5