model_name: RecurrentGAN # RNN, ES, ARIMA, GAN, ConvGAN, RecurrentGAN, RecurrentConvGAN, RecurrentConvDSGAN
loss_function: w # kl, w, ds

epochs: 20000
batch_size: 32
learning_rate: 0.001
discriminator_epochs: 10

layers: rnn  # rnn, lstm, gru
generator_nodes: 64
discriminator_nodes: 128
batch_norm: True # True, False
dropout: False # True, False
noise_vector_size: 100
noise_type: gaussian # gaussian (default), uniform

window_size: 24
forecast_horizon: 24
recurrent_forecasting: True # True, False
mc_forward_passes: 1000
plot_rate: 25

print_coverage: True # True, False, Will slow down training, but print coverage during training
save_model_interval: 100

data_source: oslo # sine, oslo, australia
val_split: 0.1
test_split: 0.2
scaler: MinMax # MinMax (default), Robust, Standard

new_training_loop: True #True, False
mixed_batches: False

cross_validation_setup:
  k-folds: 5